
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  INVENTREE_HOST: {{ include "inventree.host" . | quote }}
  INVENTREE_SKIP_INSTALL: {{ ternary "yes" "no" .Values.inventree.skipInstall | quote }}
  INVENTREE_SITE_NAME: {{ .Values.siteName | quote }}
  INVENTREE_USERNAME: {{ .Values.auth.username | quote }}
  INVENTREE_EMAIL: {{ .Values.auth.email | quote }}
  INVENTREE_REDIS_HOST: {{ include "inventree.redis.host" . }}
  INVENTREE_REDIS_PORT_NUMBER: {{ include "inventree.redis.port" . }}
  INVENTREE_DB_HOST: {{ include "inventree.database.host" . }}
  INVENTREE_DB_PORT: {{ include "inventree.database.port" . }}
  INVENTREE_DB_NAME: {{ include "inventree.database.name" . }}
  INVENTREE_DB_USER: {{ include "inventree.database.user" . }}
  INVENTREE_DB_ENGINE: "postgresql"
  INVENTREE_PLUGINS_ENABLED: "True"
  {{- if .Values.smtp.enabled }}
  INVENTREE_SMTP_HOST: {{ .Values.smtp.host | quote }}
  INVENTREE_SMTP_PORT: {{ .Values.smtp.port | quote }}
  {{- if .Values.smtp.user }}
  INVENTREE_SMTP_USER: {{ .Values.smtp.user | quote }}
  {{- end }}
  {{- if .Values.smtp.protocol }}
  INVENTREE_SMTP_PROTOCOL: {{ .Values.smtp.protocol | quote }}
  {{- end }}
  {{- if .Values.smtp.auth }}
  INVENTREE_SMTP_AUTH: {{ .Values.smtp.auth | quote }}
  {{- end }}
  {{- end }}
  {{- if or .Values.postgresql.enabled .Values.externalDatabase.create }}
  POSTGRESQL_CLIENT_DATABASE_HOST: {{ include "inventree.database.host" . }}
  POSTGRESQL_CLIENT_DATABASE_PORT_NUMBER: {{ include "inventree.database.port" . }}
  {{- if or .Values.postgresql.enabled (not .Values.externalDatabase.postgresUser) }}
  POSTGRESQL_CLIENT_POSTGRES_USER: "postgres"
  {{- else }}
  POSTGRESQL_CLIENT_POSTGRES_USER: {{ .Values.externalDatabase.postgresUser | quote }}
  POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME: {{ .Values.externalDatabase.user | quote }}
  {{- end }}
  POSTGRESQL_CLIENT_CREATE_DATABASE_NAME: {{ include "inventree.database.name" . }}
  POSTGRESQL_CLIENT_CREATE_DATABASE_EXTENSIONS: "hstore,pg_trgm"
  {{- end }}
